# Generated by Django 5.2.8 on 2025-11-30 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingElement',
            fields=[
                ('globalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('current_state', models.CharField(choices=[('RE', 'Ready for Construction'), ('UC', 'Under Construction'), ('CO', 'Completed'), ('DE', 'Delayed'), ('PL', 'Planned')])),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('buildingelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bim.buildingelement')),
                ('geometry', models.CharField(choices=[('C', 'Circular'), ('SQ', 'Square'), ('RE', 'Rectengular')])),
            ],
            bases=('bim.buildingelement',),
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('buildingelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bim.buildingelement')),
                ('color', models.CharField()),
            ],
            bases=('bim.buildingelement',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('globalId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('x', models.DecimalField(decimal_places=2, max_digits=8)),
                ('y', models.DecimalField(decimal_places=2, max_digits=8)),
                ('building_elements', models.ManyToManyField(to='bim.buildingelement')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bim.floor')),
            ],
        ),
        migrations.AddField(
            model_name='buildingelement',
            name='zones',
            field=models.ManyToManyField(to='bim.zone'),
        ),
    ]
