# Generated by Django 5.2.8 on 2025-12-06 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Generic Building Element', max_length=100)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('personResponsible', models.CharField(default='Sicco Oortwijn', max_length=100)),
                ('current_state', models.CharField(choices=[('RE', 'Ready for Construction'), ('UC', 'Under Construction'), ('CO', 'Completed'), ('DE', 'Delayed'), ('PL', 'Planned')], default='PL')),
                ('geometry', models.CharField(choices=[('C', 'Circular'), ('SQ', 'Square'), ('RE', 'Rectengular')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('storey', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Generic Building Element', max_length=100)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('personResponsible', models.CharField(default='Sicco Oortwijn', max_length=100)),
                ('current_state', models.CharField(choices=[('RE', 'Ready for Construction'), ('UC', 'Under Construction'), ('CO', 'Completed'), ('DE', 'Delayed'), ('PL', 'Planned')], default='PL')),
                ('color', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('x', models.DecimalField(decimal_places=2, max_digits=8)),
                ('y', models.DecimalField(decimal_places=2, max_digits=8)),
                ('columns', models.ManyToManyField(to='bim.column')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bim.floor')),
                ('walls', models.ManyToManyField(to='bim.wall')),
            ],
        ),
        migrations.AddField(
            model_name='wall',
            name='zones',
            field=models.ManyToManyField(to='bim.zone'),
        ),
        migrations.AddField(
            model_name='column',
            name='zones',
            field=models.ManyToManyField(to='bim.zone'),
        ),
    ]
