# Generated by Django 5.2.8 on 2025-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingelement',
            name='personResponsible',
            field=models.CharField(default='Sicco', max_length=100),
        ),
    ]
