# Generated by Django 5.2.8 on 2025-12-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim', '0002_buildingelement_personresponsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingelement',
            name='personResponsible',
            field=models.CharField(default='Sicco Oortwijn', max_length=100),
        ),
    ]
