# Generated by Django 5.2.8 on 2025-12-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim', '0002_column_progresspercentage_wall_progresspercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='progressPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wall',
            name='progressPercentage',
            field=models.IntegerField(default=0),
        ),
    ]
