# Generated by Django 5.2.8 on 2025-12-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bim', '0004_alter_buildingelement_globalid_alter_floor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='id',
            new_name='globalId',
        ),
    ]
